### Задание 1  
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [3]:
import pandas as pd

In [65]:
rating = pd.read_csv('/home/denis/MyProjects/Netology/HomeWork/12_pandas/ml-latest-small/ratings.csv')
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [6]:
film = pd.read_csv('/home/denis/MyProjects/Netology/HomeWork/12_pandas/ml-latest-small/movies.csv')

In [64]:
film.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [85]:
films_rating = pd.merge(film, rating, on=('movieId'))

In [87]:
films_rating.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483

In [90]:
filter_5_star = films_rating[ films_rating.rating == 5 ]
filter_5_star['title'].value_counts().head()

Shawshank Redemption, The (1994)             153
Pulp Fiction (1994)                          123
Forrest Gump (1994)                          116
Matrix, The (1999)                           109
Star Wars: Episode IV - A New Hope (1977)    104
Name: title, dtype: int64

### Задание 2  
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [4]:
power = pd.read_csv('/home/denis/MyProjects/Netology/LECTURE/11/power.csv')

In [49]:
filter_power = power[(power.country.isin(['Latvia', 'Lithuania', 'Estonia']))&(power.category.isin([4, 12, 21]))&(power.year>= 2005)&(power.year<= 2010)&(power.quantity>=0)]

In [51]:
filter_power.quantity.sum()

240580.0

### Задание 3  
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [63]:
page_url = 'https://www.finanz.ru/valyuty/v-realnom-vremeni'

In [74]:
df = pd.read_html(page_url, attrs = {'class': 'quote_list'}, encoding='utf-8')

In [85]:
df[0].iloc[:, 1:]

,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,GBP/RUB,892583,-,894699,"-0,24 %",-02116,08.07.2020
1,EUR/RUB,803235,-,805130,"-0,24 %",-01895,08.07.2020
2,USD/RUB,711771,-,714700,"-0,41 %",-02929,08.07.2020
3,JPY/RUB,06619,-,06630,"-0,17 %",-00011,08.07.2020
4,CNY/RUB,101407,-,101657,"-0,25 %",-00250,08.07.2020
5,CHF/RUB,755970,-,756441,"-0,06 %",-00471,08.07.2020
6,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,EUR/USD,11286,-,11275,"0,10 %",00011,08.07.2020
8,EUR/GBP,08997,-,08985,"0,13 %",00012,08.07.2020
9,EUR/JPY,1213350,-,1212500,"0,07 %",00850,08.07.2020
10,EUR/CHF,10625,-,10631,"-0,06 %",-00006,08.07.2020
11,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,USD/EUR,08861,-,08870,"-0,10 %",-00009,08.07.2020
13,USD/GBP,07972,-,07969,"0,03 %",00003,08.07.2020
14,USD/JPY,1075050,-,1075420,"-0,03 %",-00370,08.07.2020
15,USD/CHF,09413,-,09426,"-0,14 %",-00013,08.07.2020
16,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,JPY/EUR (100:1),08200,-,08200,"-0,06 %",00000,08.07.2020
18,JPY/GBP,00074,-,00074,"0,06 %",00000,08.07.2020
19,JPY/USD,00093,-,00093,"0,03 %",00000,08.07.2020
20,JPY/CHF (100:1),08800,-,08800,"-0,14 %",00000,08.07.2020
21,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,GBP/USD,12544,-,12549,"-0,04 %",-00005,08.07.2020
23,GBP/JPY,1348498,-,1349437,"-0,07 %",-00939,08.07.2020
24,GBP/EUR,11115,-,11132,"-0,15 %",-00017,08.07.2020
25,GBP/CHF,11809,-,11831,"-0,19 %",-00022,08.07.2020
26,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,GBP/CHF,11809,-,11831,"-0,19 %",-00022,08.07.2020
28,EUR/CHF,10625,-,10631,"-0,06 %",-00006,08.07.2020
29,JPY/CHF (100:1),08800,-,08800,"-0,14 %",00000,08.07.2020
30,USD/CHF,09413,-,09426,"-0,14 %",-00013,08.07.2020
31,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,EUR/UAH,304074,-,303735,"0,11 %",00339,08.07.2020
33,USD/UAH,269438,-,269400,"0,01 %",00038,08.07.2020
34,CHF/UAH,286209,-,285805,"0,14 %",00404,08.07.2020
35,GBP/UAH,337956,-,338043,"-0,03 %",-00088,08.07.2020